import {useEffect,useRef,useState} from 'react';
import {gpsStep,gpsTime,gpsUnits,type GpsPoint,type GpsWorkout} from './gps-math';
type Draft={date:string;activity:'Run'|'Bike';startedAt:string;seconds:number;meters:number;maxSpeed:number;gaps:number};
const key='t4l:gps-draft';
export function useGpsTracker(onSave:(date:string,workout:GpsWorkout)=>Promise<void>) {
 const [draft,setDraft]=useState<Draft|null>(null);const ref=useRef<Draft|null>(null);const [running,setRunning]=useState(false);const [pending,setPending]=useState(false);const [saving,setSaving]=useState(false);const savingRef=useRef(false);const [notice,setNotice]=useState('');const [saved,setSaved]=useState<GpsWorkout|null>(null);const [speed,setSpeed]=useState<number|null>(null);const [unit,setUnit]=useState<'mi'|'km'>('mi');
 const watch=useRef<number|null>(null);const last=useRef<GpsPoint|null>(null);const clock=useRef<number|null>(null);const fixAt=useRef(0);const signalTimestamp=useRef<number|undefined>(undefined);
 const persist=(d:Draft|null)=>{ref.current=d;setDraft(d);try{if(d)localStorage.setItem(key,JSON.stringify(d));else localStorage.removeItem(key);}catch{setNotice('Device storage is unavailable. Keep this page open until you save totals.');}};
 const stop=()=>{if(watch.current!==null){navigator.geolocation.clearWatch(watch.current);watch.current=null;}if(clock.current!==null&&ref.current){persist({...ref.current,seconds:ref.current.seconds+Math.max(0,(Date.now()-clock.current)/1000)});}clock.current=null;last.current=null;signalTimestamp.current=undefined;setSpeed(null);setRunning(false);setPending(false);};
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const d=JSON.parse(raw);if(/^\d{4}-\d{2}-\d{2}$/.test(d.date)&&['Run','Bike'].includes(d.activity)&&Number.isFinite(Date.parse(d.startedAt))&&['seconds','meters','maxSpeed','gaps'].every(k=>Number.isFinite(d[k])&&d[k]>=0)){ref.current=d;setDraft(d);setNotice('Recovered paused tracking. Resume or save your totals.');}}}catch{};const visibility=()=>{if(document.hidden&&(watch.current!==null||clock.current!==null)){stop();setNotice('Tracking paused while the app was hidden. Resume when ready.');}};document.addEventListener('visibilitychange',visibility);const interval=window.setInterval(()=>{if(clock.current!==null&&ref.current){const now=Date.now();persist({...ref.current,seconds:ref.current.seconds+Math.max(0,(now-clock.current)/1000)});clock.current=now;if(now-fixAt.current>10000)setSpeed(null);}},1000);return()=>{stop();clearInterval(interval);document.removeEventListener('visibilitychange',visibility);};},[]);
 useEffect(()=>{if(!running)return;let cancelled=false;let lock:{release:()=>Promise<void>}|undefined;const wake=navigator as Navigator & {wakeLock?:{request:(type:string)=>Promise<{release:()=>Promise<void>}>}};wake.wakeLock?.request('screen').then(result=>{if(cancelled)void result.release();else lock=result;}).catch(()=>{});return()=>{cancelled=true;void lock?.release();};},[running]);
 function start(date:string,activity:'Run'|'Bike') {if(watch.current!==null||savingRef.current)return;if(!navigator.geolocation){setNotice('Location tracking is unavailable on this device.');return;}if(!ref.current)persist({date,activity,startedAt:new Date().toISOString(),seconds:0,meters:0,maxSpeed:0,gaps:0});setSaved(null);setPending(true);setNotice('Waiting for GPS permission and a clear signal…');last.current=null;
 watch.current=navigator.geolocation.watchPosition(position=>{if(watch.current===null||!ref.current)return;const point={latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy,timestamp:position.timestamp,speed:position.coords.speed};const step=gpsStep(last.current,point,ref.current.activity,signalTimestamp.current);if(!step.accepted){setSpeed(null);setNotice('GPS signal is weak or inconsistent. Distance is waiting for a reliable fix.');return;}if(clock.current===null){clock.current=Date.now();setRunning(true);setPending(false);}signalTimestamp.current=point.timestamp;if(!last.current||step.meters>0||step.gap)last.current=point;fixAt.current=Date.now();setSpeed(step.speed);persist({...ref.current,meters:ref.current.meters+step.meters,maxSpeed:Math.max(ref.current.maxSpeed,step.speed||0),gaps:ref.current.gaps+(step.gap?1:0)});setNotice(step.gap?'GPS gap detected; the missing route segment was not counted.':'GPS connected');},error=>{stop();setNotice(error.code===1?'Location permission denied. Allow location in Safari settings to track.':'GPS signal unavailable. Tracking paused; you can resume or save totals.');},{enableHighAccuracy:true,maximumAge:0,timeout:15000});
 }
 async function finish(){if(!ref.current||savingRef.current)return;savingRef.current=true;setSaving(true);stop();try{const d=ref.current!;const result={id:crypto.randomUUID(),activity:d.activity,startedAt:d.startedAt,endedAt:new Date().toISOString(),seconds:d.seconds,meters:d.meters,maxSpeed:d.maxSpeed,gaps:d.gaps};await onSave(d.date,result);setSaved(result);persist(null);setNotice('GPS totals saved to your workout. Use Finish + Backup when the whole workout is done.');}catch{setNotice('Could not save totals. Your paused tracking is kept; try again.');}finally{savingRef.current=false;setSaving(false);}}
 return {draft,saved,running,pending,saving,notice,speed,unit,setUnit,start,pause:stop,finish,discard:()=>{stop();persist(null);setSaved(null);setNotice("Unsaved GPS tracking discarded. Saved workouts are unchanged.");}};
}
export function GpsTracker({tracker,date}:{tracker:ReturnType<typeof useGpsTracker>;date:string}) {const [activity,setActivity]=useState<'Run'|'Bike'>('Run');const t=tracker;const data=t.draft||t.saved;const totals=gpsUnits(data?.meters||0,data?.seconds||0,t.unit);const current=t.speed===null?'—':(t.speed*3600/(t.unit==='mi'?1609.344:1000)).toFixed(1);
 return <details className="gps-card" open={Boolean(t.draft||t.saved)}><summary><span><b>Track a run or ride</b><small>{t.draft?`${t.draft.activity} · ${t.running?'Recording':t.pending?'Connecting':'Paused'}`:t.saved?'GPS totals saved':'Live time, distance and speed · iPhone GPS'}</small></span><span aria-hidden="true">⌖</span></summary><div className="gps-body"><p>Keep the app visible for tracking. It pauses when hidden. GPS routes aren’t uploaded. Only totals are saved.</p>{t.draft&&t.draft.date!==date&&<p>Tracking belongs to {t.draft.date}; totals will save to that day.</p>}<div className="gps-options"><label>Activity<select disabled={Boolean(t.draft)} value={t.draft?.activity||activity} onChange={e=>setActivity(e.target.value as 'Run'|'Bike')}><option>Run</option><option>Bike</option></select></label><label>Units<select value={t.unit} onChange={e=>t.setUnit(e.target.value as 'mi'|'km')}><option value="mi">Miles / mph</option><option value="km">Kilometers / km/h</option></select></label></div><dl className="gps-metrics"><div><dt>Elapsed time</dt><dd>{gpsTime(data?.seconds||0)}</dd></div><div><dt>Distance</dt><dd>{totals.distance}<small> {t.unit}</small></dd></div><div><dt>Current speed</dt><dd>{current}<small> {t.unit==='mi'?'mph':'km/h'}</small></dd></div><div><dt>Average speed</dt><dd>{totals.average}<small> {t.unit==='mi'?'mph':'km/h'}</small></dd></div></dl><p className="gps-caption">Average includes stops while recording; pauses are excluded. GPS measurements are estimates.{t.draft?.gaps ? ` ${t.draft.gaps} signal gaps; distance may be incomplete.`:''}</p><div className="gps-actions">{t.running||t.pending?<button disabled={t.saving} onClick={t.pause}>Pause GPS</button>:<button disabled={t.saving} onClick={()=>t.start(date,activity)}>{t.draft?'Resume GPS':'Start GPS'}</button>}{t.draft&&<button disabled={t.saving||t.pending} onClick={()=>void t.finish()}>{t.saving?'Saving…':'Stop + save totals'}</button>}{t.draft&&!t.running&&!t.pending&&<button disabled={t.saving} onClick={()=>{if(!(t.draft!.seconds||t.draft!.meters)||window.confirm('Discard these unsaved GPS totals? Your saved workouts will stay unchanged.'))t.discard();}}>Discard unsaved tracking</button>}</div>{t.notice&&<p role="status">{t.notice}</p>}</div></details>;
}
