import type { HistoryFilters, JournalSearchEntry } from './history-search';
import { emptyHistoryFilters, searchJournal } from './history-search';
export function HistorySearchPanel({ entries, filters, onChange, today, onOpen }: { entries: JournalSearchEntry[]; filters: HistoryFilters; onChange: (filters: HistoryFilters) => void; today: string; onOpen: (date: string) => void }) {
  const active = Boolean(filters.query.trim() || filters.type || filters.from || filters.to);
  const results = active ? searchJournal(entries, filters, today) : [];
  const patch = (change: Partial<HistoryFilters>) => onChange({ ...filters, ...change });
  return <section className="journal-search" aria-label="Search journal">
    <div className="journal-search-bar"><input type="search" aria-label="Search your journal" placeholder="Search your journal" value={filters.query} onChange={e => patch({ query: e.target.value })}/><button aria-expanded={filters.expanded} aria-controls="journal-filters" onClick={() => patch({ expanded: !filters.expanded })}>Filters{filters.type || filters.from || filters.to ? ' •' : ''}</button></div>
    {filters.expanded && <div id="journal-filters" className="journal-filters"><label>Workout type<select aria-label="Workout type" value={filters.type} onChange={e => patch({ type: e.target.value })}><option value="">All types</option>{[...new Set(entries.filter(e => e.session.date <= today).map(e => e.theme))].sort().map(theme => <option key={theme}>{theme}</option>)}</select></label><label>From<input type="date" max={filters.to || today} value={filters.from} onChange={e => patch({ from: e.target.value })}/></label><label>Through<input type="date" min={filters.from} max={today} value={filters.to} onChange={e => patch({ to: e.target.value })}/></label></div>}
    {active && <><div className="journal-results-heading"><span role="status">{results.length} {results.length === 1 ? 'entry' : 'entries'} found</span><button onClick={() => onChange({ ...emptyHistoryFilters, expanded: filters.expanded })}>Clear search</button></div>{filters.from && filters.to && filters.from > filters.to ? <p>Choose an end date on or after the start date.</p> : results.length ? <div className="journal-search-results">{results.map(({session, theme, excerpt}) => <button key={session.id} onClick={() => onOpen(session.date)}><span><time>{new Date(`${session.date}T12:00:00`).toLocaleDateString('en-US', {month:'short', day:'numeric', year:'numeric'})}</time><strong>{theme}</strong><small>{excerpt}</small></span><i aria-hidden="true">›</i></button>)}</div> : <p className="empty-state">No entries match. Try another word or broaden your filters.</p>}</>}
  </section>;
}
