import {useState} from 'react';
import {localProgress, type ProgressEntry} from './local-progress';
import {adventureBackgroundFor} from './adventure-scenes';
const areas=[['strength','Full-body strength'],['endurance','Endurance'],['speed','Speed'],['aerobic','Easy aerobic'],['mobility','Mobility'],['rest','Recovery']];
const formatDate=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
export function LocalProgressView({entries,today,library,onOpen,onAdd,weeks,setWeeks}:{weeks:number;setWeeks:(weeks:number)=>void;entries:ProgressEntry[];today:string;library:string[];onOpen:(date:string)=>void;onAdd:(name:string)=>Promise<string>}) {
 const [notice,setNotice]=useState('');const [adding,setAdding]=useState(false);
 const data=localProgress(entries,today,weeks,library);
 const missing=areas.filter(([key])=>!data.counts.get(key)).map(([,label])=>label.toLowerCase());
 const custom=[...data.counts.keys()].filter(key=>!areas.some(([k])=>k===key));
 const maximum=Math.max(1,...data.counts.values(),data.supporting);
 return <div className="local-progress">
  <header className="progress-intro"><span className="kicker">YOUR TRAINING</span><h1>Your progress</h1><p>See your training balance, compare workouts, and revisit what works.</p><div className="progress-period" aria-label="Progress period">{[4,12].map(n=><button key={n} aria-pressed={weeks===n} onClick={()=>setWeeks(n)}>{n} weeks</button>)}</div></header>
  <section className="progress-balance"><header><span className="kicker">YOUR TRAINING BALANCE</span><h2>{data.finished.length ? `${data.finished.length} ${data.finished.length===1?'day':'days'} completed`:'Your progress starts with a recorded day.'}</h2><p>{data.finished.length ? missing.length ? `No completed ${missing.join(', ')} days recorded in this period.`:'You’ve recorded every part of your training mix.': 'Complete workouts to see your training mix take shape here.'}</p></header>
   <div className="progress-balance-rows">{[...areas,...custom.map(key=>[key,entries.find(e=>e.key===key)?.theme||'Custom workout'])].map(([key,label])=><div className="progress-balance-row" key={key}><div className="progress-terrain" aria-hidden="true" style={adventureBackgroundFor(key)}/><div><div className="progress-row-label"><strong>{label}</strong><span>{data.counts.get(key)||0} {(data.counts.get(key)||0)===1?'day':'days'}</span></div><div className="progress-count-track" aria-hidden="true"><i style={{width:`${(data.counts.get(key)||0)/maximum*100}%`}}/></div></div></div>)}</div>
   <footer><strong>{data.supporting} {data.supporting===1?'day':'days'} with completed add-ons</strong><p>Completed workouts and recorded recovery days. Add-ons count separately; selected exercises aren’t counted as done.</p></footer>
  </section>
  <details className="progress-detail"><summary><span><b>Compare similar workouts</b><small>{data.comparisons.length ? `${data.comparisons.length} workout ${data.comparisons.length===1?'type':'types'} to explore`:'Build a pair of matching workouts'}</small></span><i>⌄</i></summary><div className="progress-detail-body"><p>Latest two completed sessions with the same workout type and activities in this period. Read the context alongside the numbers.</p>{data.comparisons.length ? data.comparisons.map(c=><article className="progress-comparison" key={c.theme}><h3>{c.theme}</h3><div className="progress-compare-grid">{[c.prior,c.latest].map((s,index)=><div key={s.date}><span className="kicker">{index?'LATEST':'PREVIOUS'}</span><button onClick={()=>onOpen(s.date)}>{formatDate(s.date)} ↗</button><strong>{s.activity}</strong><dl>{[['Duration',s.duration],['Distance',s.distance],['Pace',s.pace],['Effort',s.effort]].filter(([,v])=>v).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{s.notes&&<p>{s.notes}</p>}<small>{s.completedExercises?.length||0} add-ons completed</small></div>)}</div></article>):<p>Record two completed workouts with matching types and activities to compare them here.</p>}</div></details>
  <details className="progress-detail"><summary><span><b>Add-ons to revisit</b><small>{data.revisit.length?'Familiar movements out of rotation':'Your supporting work, remembered'}</small></span><i>⌄</i></summary><div className="progress-detail-body"><p>Previously completed library exercises with no completion recorded in at least 14 days. Choose what fits today.</p>{data.revisit.length ? data.revisit.map(item=><div className="progress-revisit" key={item.name}><div><strong>{item.name}</strong><small>{item.days} days since recorded completion</small><button onClick={()=>onOpen(item.date)}>View last session ↗</button></div><button disabled={adding} onClick={async()=>{setAdding(true);try{setNotice(await onAdd(item.name));}catch{setNotice('Could not save. Please try again.');}finally{setAdding(false);}}}>Add to today</button></div>):<p>No previously completed library exercises are outside that window.</p>}{notice&&<p role="status">{notice}</p>}</div></details>
 </div>;
}
